#!/bin/sh


set -eu

{
  uncompress() { tar xvz - -C "${PREFIX}" --strip-components=1; }
  
  umask 002
  owner="j5pu"
  repo="Shared"
  url="https://github.com/${owner}/${repo}"
  tarball="${url}/tarball/main"
  
  : "${PREFIX:=/Users/${name}}"

  if [ "${0##*/}" = "install" ]; then
    cd "$(dirname "$0")"
    ! test -d "${PREFIX}/.git" || exit 0
    ! command -v "${name}" >/dev/null || PATH="$(dirname "$0"):${PATH}"
  else
    tmp="$(mktemp -d)"
    if command -v git >/dev/null; then
      git -C "${tmp}" clone --quiet --recurse "${url}"
    elif command -v curl > /dev/null; then
      curl -fsSL "${tarball}" | uncompress
    elif command -v curl > /dev/null; then
      wget -qO- "${tarball}" | uncompress
    fi
    downloaded=false
  fi

}
