#!/bin/sh

#
# Shared installer

set -eu

{

install() {
  cd "${src:-${tmp}}"
  . ./etc/profile
  ! test -d "${STOW_DIR?}/.git" || exit 0
  unset BASH_ENV
}

uncompress() { tar xz - -C "${src:-${tmp}}" --strip-components=1; }

main() {
  umask 002

  owner="j5pu"
  repo="Shared"
  script="${0##*/}"
  url="https://github.com/${owner}/${repo}"
  tarball="${url}/tarball/main"

  case "${script}" in
    *sh)
      tmp="$(mktemp -d)"
      trap 'rm -rf "${tmp}"' EXIT

      if command -v wget > /dev/null; then
        wget -qO- "${tarball}" | uncompress
      elif command -v git >/dev/null; then
        git -C "${tmp}" clone --quiet "${url}"
        src="${tmp}/${repo}"
      elif command -v curl > /dev/null; then
        curl -fsSL "${tarball}" | uncompress
      elif command -v wget > /dev/null; then
        wget -qO- "${tarball}" | uncompress
      fi
      install "$@"
      ;;
    *)
      src="$(dirname "${0}")"
      install "$@"
      ;;
  esac
}

main "$@"

}
